# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Url.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tUrl.proto\x12\x05urlrn\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n\nurlRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x8a\x01\n\x0burlResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0burlOriginal\x18\x02 \x01(\t\x12\x0e\n\x06titulo\x18\x03 \x01(\t\x12\x17\n\x0fusernameCreador\x18\x04 \x01(\t\x12\x31\n\rfechaCreacion\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"/\n\x0blistadoUrls\x12 \n\x04urls\x18\x01 \x03(\x0b\x32\x12.urlrn.urlResponse2v\n\nUrlService\x12\x34\n\x0bobtenerUrls\x12\x11.urlrn.urlRequest\x1a\x12.urlrn.listadoUrls\x12\x32\n\x08\x63rearUrl\x12\x12.urlrn.urlResponse\x1a\x12.urlrn.urlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Url_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_URLREQUEST']._serialized_start=53
  _globals['_URLREQUEST']._serialized_end=83
  _globals['_URLRESPONSE']._serialized_start=86
  _globals['_URLRESPONSE']._serialized_end=224
  _globals['_LISTADOURLS']._serialized_start=226
  _globals['_LISTADOURLS']._serialized_end=273
  _globals['_URLSERVICE']._serialized_start=275
  _globals['_URLSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
