# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Url_pb2 as Url__pb2


class UrlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.obtenerUrls = channel.unary_unary(
                '/urlrn.UrlService/obtenerUrls',
                request_serializer=Url__pb2.urlRequest.SerializeToString,
                response_deserializer=Url__pb2.listadoUrls.FromString,
                )
        self.crearUrl = channel.unary_unary(
                '/urlrn.UrlService/crearUrl',
                request_serializer=Url__pb2.urlResponse.SerializeToString,
                response_deserializer=Url__pb2.urlResponse.FromString,
                )


class UrlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def obtenerUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def crearUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'obtenerUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.obtenerUrls,
                    request_deserializer=Url__pb2.urlRequest.FromString,
                    response_serializer=Url__pb2.listadoUrls.SerializeToString,
            ),
            'crearUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.crearUrl,
                    request_deserializer=Url__pb2.urlResponse.FromString,
                    response_serializer=Url__pb2.urlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'urlrn.UrlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UrlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def obtenerUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/urlrn.UrlService/obtenerUrls',
            Url__pb2.urlRequest.SerializeToString,
            Url__pb2.listadoUrls.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def crearUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/urlrn.UrlService/crearUrl',
            Url__pb2.urlResponse.SerializeToString,
            Url__pb2.urlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
